version: "3.8"
services:
  nginx:
    container_name: mixedreeftank-nginx
    hostname: mixedreeftank.local
    image: nginx:1.23
    command: nginx -g "daemon off;"
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  php:
    container_name: mixedreeftank-php
    build: ./
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html
      - ./php.ini/:/usr/local/etc/php/conf.d/custom.ini
    working_dir: /var/www/html

  mysql:
    container_name: mixedreeftank-mysql
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mixedreeftank
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    container_name: mixedreeftank-phpmyadmin
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: password

volumes:
  db_data: {}

networks:
  mixedreeftank_net:
    driver: bridge
